apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatbot-demo.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "chatbot-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  chatbot-direct-api-key: {{ .Values.chatbot.directApiKey | quote }}
  chatbot-faig-api-key: {{ .Values.chatbot.faigApiKey | quote }}
