apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-https-gateway.name" . }}-tls
  labels:
    app.kubernetes.io/name: {{ include "demo-https-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{ .Values.tls.cert | indent 4 }}
  tls.key: |
{{ .Values.tls.key | indent 4 }}
