apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-https-gateway.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "demo-https-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "demo-https-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
{{- range .Values.routes }}
    - name: {{ .name | trunc 15 | trimSuffix "-" }}
      port: {{ .externalPort }}
      targetPort: {{ .externalPort }}
      nodePort: {{ .externalPort }}
      protocol: TCP
{{- end }}
