apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litellm-demo.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "litellm-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
{{ .Values.litellm.config | indent 4 }}
  custom_callbacks.py: |
{{ .Values.litellm.customCallbacks | indent 4 }}
  instruction-profiles.yaml: |
{{ .Values.litellm.instructionProfiles | indent 4 }}

