---
fortiweb_status_verbose: false
fortiweb_status_vdom: "{{ fortiweb_vdom | default('root') }}"
fortiweb_terraform_dir: "{{ (playbook_dir + '/../../terraform/aws-fortiweb') | realpath }}"
fortiweb_no_log: true
fortiweb_admin_username: "{{ fortiweb_username | default('admin') }}"
fortiweb_status_admin_password_override: "{{ fortiweb_admin_password_override | default('') }}"
fortiweb_status_system_path: /api/v2.0/system/status.systemstatus
fortiweb_status_admin_settings_path: /api/v2.0/system/admin.settings
fortiweb_status_interfaces_path: /api/v2.0/cmdb/system/interface
fortiweb_status_static_routes_path: /api/v2.0/cmdb/router/static
fortiweb_status_traffic_log_path: /api/v2.0/cmdb/log/traffic-log
fortiweb_status_disk_log_path: /api/v2.0/cmdb/log/disk
